// template-vue-ts/frontend/components/Counter.vue
<script setup lang="ts">
import { useCanister } from "@connect2ic/vue"
import { ref, watchEffect } from "vue"

let count = ref()
const [counter] = useCanister("counter")

const refreshCounter = async () => {
  const freshCount = await counter.value.getValue()
  count.value = freshCount
}

const increment = async () => {
  await counter.value.increment()
  await refreshCounter()
}

watchEffect(() => {
  if (counter.value) {
    refreshCounter()
  }
})

</script>
<template>
  <div class="example">
    <p style="font-size: 2.5em">{{ count?.toString() }}</p>
    <button class="connect-button" @click="increment">+</button>
  </div>
</template>

// template-svelte/frontend/components/Counter.svelte
<script>
  import { useCanister } from "@connect2ic/svelte"

  let count
  const [counter, { loading }] = useCanister("counter")

  const refreshCounter = async () => {
    const freshCount = await $counter.getValue()
    count = freshCount
  }

  const increment = async () => {
    await $counter.increment()
    await refreshCounter()
  }

  $: {
    if (!$loading && $counter) {
      refreshCounter()
    }
  }

</script>
<div class="example">
  <p style="font-size: 2.5em;">{count?.toString()}</p>
  <button class="connect-button" on:click={increment}>+</button>
</div>
