// template-react-ts/frontend/components/Transfer.tsx
import React from "react"
import { useWallet, useTransfer } from "@connect2ic/react"

const Transfer = () => {

  const [wallet] = useWallet()
  const [transfer] = useTransfer({
    to: "9dd04c8ba6039018a7b6d569cf6192efc596a0435fdc7f6fdb2d017518360409",
    amount: Number(0.01),
  })

  const onPurchase = async () => {
    const { height } = await transfer()
  }

  return (
    <div className="example">
      {wallet ? (
        <>
          <p>Buy me beer</p>
          <button className="connect-button" onClick={onPurchase}>Purchase</button>
        </>
      ) : (
        <p className="example-disabled">Connect with a wallet to access this example</p>
      )}
    </div>
  )
}

export { Transfer }

// template-svelte-ts/frontend/components/Transfer.svelte
<script lang="ts">
  import { useWallet, useTransfer } from "@connect2ic/svelte"

  const [wallet] = useWallet()
  const [transfer] = useTransfer({
    to: "k6jaa-yr3je-rx4ge-wwk7y-sysc4-cluwg-y4fuu-lkl5h-uutjg-tcy3q-rae",
    amount: Number(0.01),
  })

  const onPurchase = async () => {
    const { height } = await transfer()
  }
</script>
<div class="example">
  {#if $wallet}
    <p>Buy me a beer</p>
    <button class="connect-button" on:click={onPurchase}>Purchase</button>
  {:else}
    <p class="example-disabled">Connect with a wallet to access this example</p>
  {/if}
</div>
