// template-vue-ts/frontend/components/Profile.vue
<script setup lang="ts">
import { useWallet, useBalance } from "@connect2ic/vue"

const [wallet] = useWallet()
const [assets] = useBalance()

</script>
<template>
  <div class="example">
    <template v-if="wallet">
      <p>Wallet address: <span style="font-size: 0.7em">{{ wallet.principal }}</span></p>
      <table>
        <tbody>
        <template v-if="assets">
          <tr v-for="asset in assets">
            <td>
              {{ asset.name }}
            </td>
            <td>
              {{ asset.amount }}
            </td>
          </tr>
        </template>
        </tbody>
      </table>
    </template>
    <template v-else>
      <p class="example-disabled">Connect with a wallet to access this example</p>
    </template>
  </div>
</template>

// template-react-ts/frontend/components/Profile.tsx
import React from "react"
import { useBalance, useWallet } from "@connect2ic/react"

const Profile = () => {

  const [wallet] = useWallet()
  const [assets] = useBalance()

  return (
    <div className="example">
      {wallet ? (
        <>
          <p>Wallet address: <span style={{ fontSize: "0.7em" }}>{wallet ? wallet.principal : "-"}</span></p>
          <table>
            <tbody>
            {assets && assets.map(asset => (
              <tr key={asset.canisterId}>
                <td>
                  {asset.name}
                </td>
                <td>
                  {asset.amount}
                </td>
              </tr>
            ))}
            </tbody>
          </table>
        </>
      ) : (
        <p className="example-disabled">Connect with a wallet to access this example</p>
      )}
    </div>
  )
}

export { Profile }
